/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_datadriven_jni_JniBase */

#ifndef _Included_cz_datadriven_jni_JniBase
#define _Included_cz_datadriven_jni_JniBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cz_datadriven_jni_JniBase
 * Method:    jniPut
 * Signature: ([BI[BI)V
 */
JNIEXPORT void JNICALL Java_cz_datadriven_jni_JniBase_jniPut
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     cz_datadriven_jni_JniBase
 * Method:    jniGet
 * Signature: ([BI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cz_datadriven_jni_JniBase_jniGet
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
